### ISSUE TITLE
3rd party keyboard SwiftKey obscure the seed input on start

### ISSUE THREAD

**Issue by Joohansson** [nano-wallet-company/nano-wallet-ios#10]
When I click to paste my seed the keyboard pop up over the actual text and I can't continue. Need to switch to default keyboard and restart app. Maybe I look into this on monday because I recently solved a similar thing in my own app which works fine with SwiftKey.

**Comment by zackshapiro** [comment]
Yeah this doesn’t support custom keyboards currently

Best,
Zack


On Jun 22, 2018 at 4:10 PM, joohansson <notifications@github.com> wrote:


When I click to paste my seed the keyboard pop up over the actual text and
I can't continue. Need to switch to default keyboard and restart app. Maybe
I look into this on monday because I recently solved a similar thing in my
own app which works fine with SwiftKey.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-ios/issues/10>, or mute
the thread

**Comment by Joohansson** [comment]
I forked the project but I see now that it was not designed with storyboard. Don't think I can help as I thought.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
