### ISSUE TITLE
Manage accounts

### ISSUE THREAD

**Issue by tiagocanto01** [nano-wallet-company/nano-wallet-ios#19]
Some people tried to import their seed but they cannot manage other accounts from this seed.
We should think about how to add this feature in the app.

**Comment by zackshapiro** [comment]
Yeah that’s multiple accounts


On Jul 6, 2018 at 6:08 PM, Tiago Canto <notifications@github.com> wrote:


Some people tried to import their seed but they cannot manage other
accounts from this seed.
We should think about how to add this feature in the app.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-ios/issues/19>, or mute
the thread

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
