### ISSUE TITLE
Display bug on iPad with EULA on initial startup

### ISSUE THREAD

**Issue by dbachm123** [nano-wallet-company/nano-wallet-ios#9]
No way to check the boxes. iPhone working fine. This is the initial release version of the wallet on an iPad Air2 running 11.3.1. 

![63b0107c-1a36-400a-82d3-c52ff8e85e7b](https://user-images.githubusercontent.com/35655469/41776606-a9717caa-75e5-11e8-95d9-726d18fe2807.jpeg)

**Comment by zackshapiro** [comment]
This version wasn’t intended for iPad

Best,
Zack

On Jun 22, 2018 at 8:32 AM, dbachm123 <notifications@github.com> wrote:


No way to check the boxes. iPhone working fine. This is the initial release
version of the wallet on an iPad Air2 running 11.3.1.

[image: 63b0107c-1a36-400a-82d3-c52ff8e85e7b]
<https://user-images.githubusercontent.com/35655469/41776606-a9717caa-75e5-11e8-95d9-726d18fe2807.jpeg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-ios/issues/9>, or mute
the thread

**Comment by dbachm123** [comment]
Ok. It says “Compatible with iPhone, iPad and iPod touch.” on the App Store page though.

**Comment by zackshapiro** [comment]
That should be fixed now. Closing
